<?binding.jca TestDB_db.jca?>
<wsdl:definitions name="TestDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TestApplication/Project1/TestDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TestApplication/Project1/TestDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/TestDB">
    <plt:partnerLinkType name="TestDB_plt">
        <plt:role name="TestDB_role">
            <plt:portType name="tns:TestDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/TestDB" schemaLocation="xsd/TestDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TestCollection_msg">
        <wsdl:part name="TestCollection" element="top:TestCollection"/>
    </wsdl:message>
    <wsdl:portType name="TestDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TestCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
